In [ ]:
import torch

In [ ]:
x= torch.tensor([[1,2,3], [4,5,6]])

print(x)

print(x.ndimension())
print(x.ndim)

print(x.size())
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
2
2
torch.Size([2, 3])
torch.Size([2, 3])


In [ ]:
print(x)
print(x.shape)

x1 = torch.unsqueeze(x, 0)
x2 = torch.unsqueeze(x, 1)
x3 = torch.unsqueeze(x, 2)
print(x1)
print(x2)
print(x3)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])


In [ ]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x.view(1,3,3))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
x=torch.tensor([[1,2],[3,4], [5,6]], dtype=torch.float)

w = torch.randn(2,1)
b = torch.randn(1)

result = torch.mm(x,w) + b
print(result)

tensor([[-0.5528],
        [ 0.1560],
        [ 0.8648]])


In [ ]:
x = torch.tensor(5.0, requires_grad=True)
y = 3*x**3 + 4*x +7

y.backward() # 미분값 
print(x.grad)


tensor(229.)


In [ ]:
x_train = torch.tensor([[1,2], [3,2], [3,7], [1,1], [1,0]], dtype=torch.float)
y_train = torch.tensor([[4], [8], [23], [1], [-2]], dtype=torch.float)
lr = 0.001
w = torch.randn(2,1)
b = torch.randn(1)
for epoch in range(5000):
  w.requires_grad_(True)
  b.requires_grad_(True)
  h = torch.mm(x_train, w) + b
  cost = torch.mean((y_train - h) ** 2)

  cost.backward()
  with torch.no_grad():
    w = w - lr * w.grad
    b = b - lr * b.grad
    if (epoch % 100 ==0):
      print(w,b,cost)

tensor([[-0.8306],
        [ 1.7340]]) tensor([0.4663]) tensor(44.9856, grad_fn=<MeanBackward0>)
tensor([[-0.1410],
        [ 3.0672]]) tensor([0.5420]) tensor(4.6743, grad_fn=<MeanBackward0>)
tensor([[-0.1179],
        [ 3.1724]]) tensor([0.3531]) tensor(4.1680, grad_fn=<MeanBackward0>)
tensor([[-0.1089],
        [ 3.2137]]) tensor([0.1688]) tensor(3.8097, grad_fn=<MeanBackward0>)
tensor([[-0.0895],
        [ 3.2428]]) tensor([-0.0017]) tensor(3.5061, grad_fn=<MeanBackward0>)
tensor([[-0.0611],
        [ 3.2640]]) tensor([-0.1600]) tensor(3.2426, grad_fn=<MeanBackward0>)
tensor([[-0.0259],
        [ 3.2788]]) tensor([-0.3077]) tensor(3.0093, grad_fn=<MeanBackward0>)
tensor([[0.0144],
        [3.2885]]) tensor([-0.4463]) tensor(2.7998, grad_fn=<MeanBackward0>)
tensor([[0.0584],
        [3.2943]]) tensor([-0.5770]) tensor(2.6093, grad_fn=<MeanBackward0>)
tensor([[0.1050],
        [3.2969]]) tensor([-0.7005]) tensor(2.4347, grad_fn=<MeanBackward0>)
tensor([[0.1534],
        [3.2971]]) te

In [ ]:
x_test = torch.tensor([[5,10]], dtype=torch.float)
h_test = torch.mm(x_test, w) +b


In [ ]:
from sklearn.linear_model import LinearRegression
x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

model = LinearRegression() # 모델 생성
model.fit(x, y) # 학습 (피팅)


LinearRegression()


In [ ]:
print(model.coef_, model.intercept_)
print(model.predict([[5,10]]))

[[2. 3.]] [-4.]
[[36.]]
