In [15]:
import torch

x_train = torch.tensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]], dtype=torch.float)
y_train = torch.FloatTensor([[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]])

W = torch.randn(4,3,requires_grad = True)
b = torch.randn(1,3,requires_grad = True)

optim = torch.optim.Adam([W,b], lr=0.1)

for epoch in range(3001):
    #h = torch.softmax(torch.mm(x_train, W) + b, dim=1)
    h = (torch.mm(x_train, W)+b).softmax(dim=1)
    #cost = torch.mean(torch.sum(-torch.log(h) * y_train, dim=1))
    cost = (-torch.log(h)*y_train).sum(dim=1).mean()

    optim.zero_grad()
    cost.backward()
    optim.step()

    with torch.no_grad():
      if epoch%300 == 0:
        print(f"epoch: {epoch}, cost: {cost.item()}")

epoch: 0, cost: 4.391642093658447
epoch: 300, cost: 0.14399978518486023
epoch: 600, cost: 0.06783723831176758
epoch: 900, cost: 0.039094168692827225
epoch: 1200, cost: 0.02520613744854927
epoch: 1500, cost: 0.01745430752635002
epoch: 1800, cost: 0.012690887786448002
epoch: 2100, cost: 0.009556088596582413
epoch: 2400, cost: 0.007385135628283024
epoch: 2700, cost: 0.005821835249662399
epoch: 3000, cost: 0.004661102779209614


In [12]:
torch.softmax(torch.mm(x_train, W), dim=1)
#y_train
torch.sum(-torch.log(h) * y_train, dim=1)

tensor([1.1976e+00, 7.3302e+00, 6.4939e+00, 6.6757e-06, 1.7218e-01, 4.6287e-03,
        6.8681e+00, 7.2193e+00], grad_fn=<SumBackward1>)

In [ ]:
x_test = torch.tensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]], dtype=torch.float)
h = (torch.mm(x_test, W) + b).softmax(dim=1)
print(torch.argmax(h,dim=1))

In [24]:
import torch
import torch.nn.functional as F
import torch.nn as nn

x_train = torch.tensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]], dtype=torch.float)
y_train = torch.tensor([2,2,2,1,1,1,0,0], dtype=torch.long)

model = torch.nn.Linear(4,3)
W = torch.randn(4,3,requires_grad = True)
b = torch.randn(1,3,requires_grad = True)

optim = torch.optim.Adam(model.parameters(), lr=0.1)

for epoch in range(3001):
    #h = torch.mm(x_train, W)+b
    h = model(x_train)
    cost = F.cross_entropy(h,y_train)

    optim.zero_grad()
    cost.backward()
    optim.step()

    with torch.no_grad():
      if epoch%300 == 0:
        print(f"epoch: {epoch}, cost: {cost.item()}")

epoch: 0, cost: 2.0765700340270996
epoch: 300, cost: 0.11452198028564453
epoch: 600, cost: 0.04621659591794014
epoch: 900, cost: 0.025005392730236053
epoch: 1200, cost: 0.015652265399694443
epoch: 1500, cost: 0.010673997923731804
epoch: 1800, cost: 0.0076949805952608585
epoch: 2100, cost: 0.005765048786997795
epoch: 2400, cost: 0.004441535100340843
epoch: 2700, cost: 0.003494447097182274
epoch: 3000, cost: 0.0027941742446273565


In [23]:
model = torch.nn.Linear(4,3)
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[-0.4771,  0.2248,  0.0249, -0.2131],
        [ 0.1850,  0.3594, -0.1053,  0.2804],
        [ 0.4363,  0.4105, -0.2854, -0.3020]], requires_grad=True)
Parameter containing:
tensor([-0.0550, -0.0755,  0.3820], requires_grad=True)


In [25]:
x_test = torch.tensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]], dtype=torch.float)
h = model(x_test)
print(torch.argmax(h,dim=1))

tensor([0, 1, 2])
